package com.api.videogames.config;

import com.api.videogames.models.Game;
import com.api.videogames.repositories.GameRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;

@Component
@RequiredArgsConstructor
public class DataSeeder implements CommandLineRunner {

    private final GameRepository gameRepository;

    @Override
    public void run(String... args) {
        if (gameRepository.count() == 0) {
            List<Game> games = List.of(
                    Game.builder()
                            .id("3498")
                            .name("Grand Theft Auto V")
                            .description("Rockstar Games went bigger, since their previous installment of the series. You get the complicated and realistic world-building from Liberty City of GTA4 in the setting of lively and diverse Los Santos, from an old fan favorite GTA San Andreas. 561 different vehicles (including every transport you can operate) and the amount is rising with every update. Simultaneous storytelling from three unique perspectives: Follow Michael, ex-criminal living his life of leisure away from the past, Franklin, a kid that seeks the better future, and Trevor, the exact past Michael is trying to run away from. GTA Online will provide a lot of additional challenge even for the experienced players, coming fresh from the story mode. Now you will have other players around that can help you just as likely as ruin your mission. Every GTA mechanic up to date can be experienced by players through the unique customizable character, and community content paired with the leveling system tends to keep everyone busy and engaged.")
                            .released(LocalDate.parse("2013-09-17"))
                            .mainImage("https://media.rawg.io/media/games/456/456dea5e1c7e3cd07060c14e96612001.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/456/456dea5e1c7e3cd07060c14e96612001.jpg", "https://media.rawg.io/media/screenshots/a7c/a7c43871a54bed6573a6a429451564ef.jpg", "https://media.rawg.io/media/screenshots/cf4/cf4367daf6a1e33684bf19adb02d16d6.jpg", "https://media.rawg.io/media/screenshots/f95/f9518b1d99210c0cae21fc09e95b4e31.jpg", "https://media.rawg.io/media/screenshots/a5c/a5c95ea539c87d5f538763e16e18fb99.jpg", "https://media.rawg.io/media/screenshots/a7e/a7e990bc574f4d34e03b5926361d1ee7.jpg", "https://media.rawg.io/media/screenshots/592/592e2501d8734b802b2a34fee2df59fa.jpg"))
                            .rating(4.47)
                            .price(782.0)
                            .priceWithSale(782.0 - (782.0 * 10 / 100))
                            .onSale(10.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Action", "Adventure"))
                            .tags(List.of("Singleplayer", "Steam Achievements", "Multiplayer", "Atmospheric", "Full controller support", "Great Soundtrack", "RPG", "Co-op", "Open World", "cooperative", "First-Person", "Third Person", "Funny", "Sandbox", "Comedy", "Third-Person Shooter", "Moddable", "Crime", "vr mod"))
                            .platforms(List.of("PC", "Xbox Series S/X", "PlayStation 4", "PlayStation 3", "Xbox 360", "Xbox One", "PlayStation 5"))
                            .build(),
                    Game.builder()
                            .id("3328")
                            .name("The Witcher 3: Wild Hunt")
                            .description("The third game in a series, it holds nothing back from the player. Open world adventures of the renowned monster slayer Geralt of Rivia are now even on a larger scale. Following the source material more accurately, this time Geralt is trying to find the child of the prophecy, Ciri while making a quick coin from various contracts on the side. Great attention to the world building above all creates an immersive story, where your decisions will shape the world around you.CD Project Red are infamous for the amount of work they put into their games, and it shows, because aside from classic third-person action RPG base game they provided 2 massive DLCs with unique questlines and 16 smaller DLCs, containing extra quests and items.Players praise the game for its atmosphere and a wide open world that finds the balance between fantasy elements and realistic and believable mechanics, and the game deserved numerous awards for every aspect of the game, from music to direction.")
                            .released(LocalDate.parse("2015-05-18"))
                            .mainImage("https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg", "https://media.rawg.io/media/screenshots/1ac/1ac19f31974314855ad7be266adeb500.jpg", "https://media.rawg.io/media/screenshots/6a0/6a08afca95261a2fe221ea9e01d28762.jpg", "https://media.rawg.io/media/screenshots/cdd/cdd31b6b4a687425a87b5ce231ac89d7.jpg", "https://media.rawg.io/media/screenshots/862/862397b153221a625922d3bb66337834.jpg", "https://media.rawg.io/media/screenshots/166/166787c442a45f52f4f230c33fd7d605.jpg", "https://media.rawg.io/media/screenshots/f63/f6373ee614046d81503d63f167181803.jpg"))
                            .rating(4.67)
                            .price(85.0)
                            .priceWithSale(85.0 - (85.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Action", "Adventure", "RPG"))
                            .tags(List.of("Singleplayer", "Atmospheric", "Full controller support", "Great Soundtrack", "RPG", "Story Rich", "Open World", "Third Person", "Fantasy", "Sandbox", "Action RPG", "Dark", "Nudity", "controller support", "Mature", "Choices Matter", "Dark Fantasy", "Medieval", "Magic", "Multiple Endings"))
                            .platforms(List.of("Nintendo Switch", "PlayStation 5", "Xbox Series S/X", "Xbox One", "PC", "PlayStation 4"))
                            .build(),
                    Game.builder()
                            .id("4200")
                            .name("Portal 2")
                            .description("Portal 2 is a first-person puzzle game developed by Valve Corporation and released on April 19, 2011 on Steam, PS3 and Xbox 360. It was published by Valve Corporation in digital form and by Electronic Arts in physical form. Its plot directly follows the first game's, taking place in the Half-Life universe. You play as Chell, a test subject in a research facility formerly ran by the company Aperture Science, but taken over by an evil AI that turned upon its creators, GladOS. After defeating GladOS at the end of the first game but failing to escape the facility, Chell is woken up from a stasis chamber by an AI personality core, Wheatley, as the unkempt complex is falling apart. As the two attempt to navigate through the ruins and escape, they stumble upon GladOS, and accidentally re-activate her...Portal 2's core mechanics are very similar to the first game's ; the player must make their way through several test chambers which involve puzzles. For this purpose, they possess a Portal Gun, a weapon capable of creating teleportation portals on white surfaces. This seemingly simple mechanic and its subtleties coupled with the many different puzzle elements that can appear in puzzles allows the game to be easy to start playing, yet still feature profound gameplay. The sequel adds several new puzzle elements, such as gel that can render surfaces bouncy or allow you to accelerate when running on them.The game is often praised for its gameplay, its memorable dialogue and writing and its aesthetic. Both games in the series are responsible for inspiring most puzzle games succeeding them, particularly first-person puzzle games. The series, its characters and even its items such as the portal gun and the companion cube have become a cultural icon within gaming communities.Portal 2 also featured a co-op mode where two players take on the roles of robots being led through tests by GladOS, as well as an in-depth level editor.")
                            .released(LocalDate.parse("2011-04-18"))
                            .mainImage("https://media.rawg.io/media/games/328/3283617cb7d75d67257fc58339188742.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/328/3283617cb7d75d67257fc58339188742.jpg", "https://media.rawg.io/media/screenshots/221/221a03c11e5ff9f765d62f60d4b4cbf5.jpg", "https://media.rawg.io/media/screenshots/173/1737ff43c14f40294011a209b1012875.jpg", "https://media.rawg.io/media/screenshots/b11/b11a2ae0664f0e8a1ef2346f99df26e1.jpg", "https://media.rawg.io/media/screenshots/9b1/9b107a790909b31918ebe2f40547cc85.jpg", "https://media.rawg.io/media/screenshots/d05/d058fc7f7fa6128916c311eb14267fed.jpg", "https://media.rawg.io/media/screenshots/415/41543dcc12dffc8e97d85a56ad42cda8.jpg"))
                            .rating(4.61)
                            .price(964.0)
                            .priceWithSale(964.0 - (964.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Shooter", "Puzzle"))
                            .tags(List.of("Singleplayer", "Steam Achievements", "Multiplayer", "Atmospheric", "steam-trading-cards", "Full controller support", "Steam Cloud", "Co-op", "Story Rich", "cooperative", "First-Person", "Sci-fi", "FPS", "Online Co-Op", "Funny", "Female Protagonist", "Comedy", "Local Co-Op", "stats", "Steam Workshop", "Space", "Includes level editor", "Captions available", "Commentary available", "Science"))
                            .platforms(List.of("Xbox 360", "Linux", "macOS", "PlayStation 3", "PC", "Xbox One"))
                            .build(),
                    Game.builder()
                            .id("5286")
                            .name("Tomb Raider (2013)")
                            .description("A cinematic revival of the series in its action third person form, Tomb Rider follows Lara in her least experience period of life – her youth. Heavily influenced by Naughty Dog’s “Uncharted”, the game is a mix of everything, from stealth and survival to combat and QTE action scenes.Young Lara Croft arrives on the Yamatai, lost island near Japan, as the leader of the expedition in search of the Yamatai Kingdom, with a diverse team of specialists. But shipwreck postponed the successful arrival and seemingly forgotten island is heavily populated with hostile inhabitants, cultists of Solarii Brotherhood.The game will be graphic at times, especially after failed QTE’s during some of the survival scenes, but overall players will enjoy classic action adventure, reminiscent of the beginning of the series. This game is not a direct sequel or continuation of existing sub-series within the franchise, but a reboot, setting up Tomb Raider to represent modern gaming experience.The game has RPG elements and has a world, which you can explore during the story campaign and after the completion. As well as multiplayer mode, where 2 teams (4 scavengers and 4 survivors) are clashing in 3 game modes while using weapons and environments from the single-player campaign.")
                            .released(LocalDate.parse("2013-03-05"))
                            .mainImage("https://media.rawg.io/media/games/021/021c4e21a1824d2526f925eff6324653.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/021/021c4e21a1824d2526f925eff6324653.jpg", "https://media.rawg.io/media/screenshots/4f9/4f9d5efdecfb63cb99f1baa4c0ceb3bf.jpg", "https://media.rawg.io/media/screenshots/80f/80f373082b2a74da3f9c3fe2b877dcd0.jpg", "https://media.rawg.io/media/screenshots/a87/a8733e877f8fbe45e4a727c22a06aa2e.jpg", "https://media.rawg.io/media/screenshots/3f9/3f91678c6805a76419fa4ea3a045a909.jpg", "https://media.rawg.io/media/screenshots/417/4170bf07be43a8d8249193883f87f1c1.jpg", "https://media.rawg.io/media/screenshots/2a4/2a4250f83ad9e959d8b4ca9376ae34ea.jpg"))
                            .rating(4.05)
                            .price(989.0)
                            .priceWithSale(989.0 - (989.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Action", "Adventure"))
                            .tags(List.of("Singleplayer", "Multiplayer", "Atmospheric", "Full controller support", "RPG", "Third Person", "Classic", "Exploration", "Female Protagonist", "Stealth", "Third-Person Shooter", "Retro", "Action-Adventure", "Cinematic", "Quick-Time Events", "Dinosaurs", "Lara Croft"))
                            .platforms(List.of("PlayStation 4", "macOS", "PC", "Xbox One", "Xbox 360", "PlayStation 3"))
                            .build(),
                    Game.builder()
                            .id("4291")
                            .name("Counter-Strike: Global Offensive")
                            .description("Counter-Strike is a multiplayer phenomenon in its simplicity. No complicated narratives to explain the source of the conflict, no futuristic and alien threats, but counter-terrorists against terrorists. Arena shooter at its core, CS:GO provides you with various methods of disposing enemies and reliant on cooperation within the team. During the round of the classical clash mode, you will gradually receive currency to purchase different equipment. Each player can carry a primary weapon, secondary pistol, knife and a set of grenades, which all can change the battle if wielded by the skilled player. Objectives are clear and vary from map to map, from game mode to game mode. Stop the terrorists from planting explosives, stop the counter-terrorist from retrieving the hostages, kill everyone who isn’t you and just perform the best with.CS:GO is one of the major cybersport discipline, which makes playing it more exciting to some players. Aside from purchasing the game, CS:GO is infamous for its loot case system, that requires players to purchase keys, in order to open said cases. Customization items consist of weapon skins, weapon stickers, and sprays that do not affect gameplay and have purely visual value to the player.")
                            .released(LocalDate.parse("2012-08-21"))
                            .mainImage("https://media.rawg.io/media/games/736/73619bd336c894d6941d926bfd563946.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/736/73619bd336c894d6941d926bfd563946.jpg", "https://media.rawg.io/media/screenshots/ff1/ff16661bb15f7969b44f6c4118870e44.jpg", "https://media.rawg.io/media/screenshots/41b/41bb769d247412eac3336dec934aed72.jpg", "https://media.rawg.io/media/screenshots/754/754545acdbf71f56e8902a07c7d20696.jpg", "https://media.rawg.io/media/screenshots/fd8/fd873cab4c66db0b8e85d8a66e940074.jpg", "https://media.rawg.io/media/screenshots/7db/7db2954f7908b6749c36a5f3c9052f65.jpg", "https://media.rawg.io/media/screenshots/337/337a3e98b5933f456a2b37b59fab5f39.jpg"))
                            .rating(3.57)
                            .price(923.0)
                            .priceWithSale(923.0 - (923.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Action", "Shooter"))
                            .tags(List.of("Steam Achievements", "Multiplayer", "steam-trading-cards", "Full controller support", "Co-op", "cooperative", "First-Person", "FPS", "Online Co-Op", "Tactical", "stats", "Steam Workshop", "Moddable", "PvP", "War", "In-App Purchases", "Team-Based", "Fast-Paced", "Realistic", "Military", "Competitive", "Valve Anti-Cheat enabled", "e-sports", "Trading"))
                            .platforms(List.of("PC", "Xbox 360", "PlayStation 3"))
                            .build(),
                    Game.builder()
                            .id("5679")
                            .name("The Elder Scrolls V: Skyrim")
                            .description("The fifth game in the series, Skyrim takes us on a journey through the coldest region of Cyrodiil. Once again player can traverse the open world RPG armed with various medieval weapons and magic, to become a hero of Nordic legends –Dovahkiin, the Dragonborn. After mandatory character creation players will have to escape not only imprisonment but a fire-breathing dragon. Something Skyrim hasn’t seen in centuries.After Oblivion, the magic system was reworked, in order to show players more aggressive and direct combat. As a Dragonborn, your character will be able to use the powerful magic of dragon shouts, powered, upgraded and researched with the souls of the dragons that will be randomly encountered by players, while traveling. Hundreds of sidequests will invite players to discover every part of the newly introduced land. Aside from already filled with guilds, Daedra and steampunk Dwemer ruins, Skyrim has additional DLC content that not only brings Solstheim island and vampire conclave but gives players the ability to build their own homes, instead of buying pre-made ones.")
                            .released(LocalDate.parse("2011-11-11"))
                            .mainImage("https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg", "https://media.rawg.io/media/screenshots/3bd/3bd2710bd1ffb6664fdea7b83afd067e.jpg", "https://media.rawg.io/media/screenshots/d4e/d4e9b13f54748584ccbd6f998094dade.jpg", "https://media.rawg.io/media/screenshots/599/59946a630e9c7871003763d63184404a.jpg", "https://media.rawg.io/media/screenshots/c5d/c5dad426038d7d12f933eedbeab48ff3.jpg", "https://media.rawg.io/media/screenshots/b32/b326fa01c82db82edd41ed299886ee44.jpg", "https://media.rawg.io/media/screenshots/091/091e95b49d5a22de036698fc731395a2.jpg"))
                            .rating(4.42)
                            .price(265.0)
                            .priceWithSale(265.0 - (265.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Action", "RPG"))
                            .tags(List.of("Singleplayer", "Steam Achievements", "Atmospheric", "steam-trading-cards", "Steam Cloud", "Great Soundtrack", "RPG", "Story Rich", "Open World", "First-Person", "Third Person", "Partial Controller Support", "Fantasy", "Sandbox", "Action RPG", "Steam Workshop", "Moddable", "role-playing", "Character Customization", "Dark Fantasy", "Medieval", "Magic", "Lore-Rich", "Dragons"))
                            .platforms(List.of("PC", "Nintendo Switch", "Xbox 360", "PlayStation 3"))
                            .build(),
                    Game.builder()
                            .id("12020")
                            .name("Left 4 Dead 2")
                            .description("Cooperative survival continues with a different set of characters. New survivors are making their way through 5 campaigns with an added ability to play through the story of the first game as well, using not only expanded arsenal of 20 ranged and 10 melee weapons but improved AI Director. Your surroundings and weather will change; enemy and item placement will differ from map to map, from difficulty to difficulty. New unique special zombies, placed in the unlucky for the player spot, can end your run.High compatibility with community mods will allow you not only to add user-created maps but player models, enemy models, and even in-game music, which will help any player to create the unique experience on top of solid game mechanics.Competitive multiplayer mods from arena survival to a head-on competition with another team of survivors are addictive and, in addition to the campaign, will provide you with hundreds of hours of game content.")
                            .released(LocalDate.parse("2009-11-17"))
                            .mainImage("https://media.rawg.io/media/games/d58/d588947d4286e7b5e0e12e1bea7d9844.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/d58/d588947d4286e7b5e0e12e1bea7d9844.jpg", "https://media.rawg.io/media/screenshots/4c0/4c043fd1a5ff78900483f2e82580fea0.jpg", "https://media.rawg.io/media/screenshots/c90/c9071628c238fbc20b366e2413dd8b4a.jpg", "https://media.rawg.io/media/screenshots/e29/e293b0f98092b8c0dbe24d66846088bb.jpg", "https://media.rawg.io/media/screenshots/168/16867bc76b385eb0fb749e41f7ada93d.jpg", "https://media.rawg.io/media/screenshots/fb9/fb917e562f311f48ff8d27632bd29a80.jpg", "https://media.rawg.io/media/screenshots/5f2/5f2ca569912add2a211b20ba3f576b97.jpg"))
                            .rating(4.08)
                            .price(601.0)
                            .priceWithSale(601.0 - (601.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Action", "Shooter"))
                            .tags(List.of("Singleplayer", "Steam Achievements", "Multiplayer", "steam-trading-cards", "Full controller support", "Steam Cloud", "Co-op", "cooperative", "First-Person", "Horror", "FPS", "Online Co-Op", "Gore", "Survival", "Local Co-Op", "Tactical", "stats", "Steam Workshop", "Zombies", "Moddable", "Post-apocalyptic", "Captions available", "Replay Value", "Survival Horror", "Team-Based", "Valve Anti-Cheat enabled", "Commentary available", "Includes Source SDK"))
                            .platforms(List.of("macOS", "Linux", "PC", "Xbox 360"))
                            .build(),
                    Game.builder()
                            .id("13536")
                            .name("Portal")
                            .description("Every single time you click your mouse while holding a gun, you expect bullets to fly and enemies to fall. But here you will try out the FPS game filled with environmental puzzles and engaging story. Silent template for your adventures, Chell, wakes up in a testing facility. She’s a subject of experiments on instant travel device, supervised by snarky and hostile GLaDOS.Players will have to complete the tests, room by room, expecting either reward, freedom or more tests. By using the gun, that shoots portals (Portal-Gun™), players will move blocks, travel great distance quickly and learn about your current situation, which is unraveled through environmental storytelling. What you will be told might be different from what you will see.White environments will guide the player’s portal placement, forcing them to pay attention to the surroundings. Portal creates tension, allowing either solving puzzles at your own leisure or moving quickly, due to the time limit or threats.")
                            .released(LocalDate.parse("2007-10-09"))
                            .mainImage("https://media.rawg.io/media/games/7fa/7fa0b586293c5861ee32490e953a4996.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/7fa/7fa0b586293c5861ee32490e953a4996.jpg", "https://media.rawg.io/media/screenshots/99e/99e94bd55eb75fa6e75c3dcbb1a570b2.jpg", "https://media.rawg.io/media/screenshots/2f0/2f0297a46934d9fa914c626902b1ce20.jpg", "https://media.rawg.io/media/screenshots/3b3/3b3713fbca6194dfc4d6e8a8d006d354.jpg", "https://media.rawg.io/media/screenshots/c6f/c6f9afc3e4dd51068b22f04acbc6ca99.jpg", "https://media.rawg.io/media/screenshots/748/74841207eec76ebc7fc03210168bfb7e.jpg", "https://media.rawg.io/media/screenshots/e72/e7256b4caedf099bcb8ebd332f892334.jpg"))
                            .rating(4.51)
                            .price(496.0)
                            .priceWithSale(496.0 - (496.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Adventure", "Puzzle"))
                            .tags(List.of("Singleplayer", "Steam Achievements", "Atmospheric", "Great Soundtrack", "Story Rich", "First-Person", "Sci-fi", "Partial Controller Support", "FPS", "Funny", "Classic", "Female Protagonist", "Comedy", "Includes level editor", "Short", "Captions available", "Physics", "Dark Humor", "Commentary available", "Includes Source SDK", "Science"))
                            .platforms(List.of("PC", "macOS", "Linux", "Xbox 360", "PlayStation 3", "Android"))
                            .build(),
                    Game.builder()
                            .id("4062")
                            .name("BioShock Infinite")
                            .description("The third game in the series, Bioshock takes the story of the underwater confinement within the lost city of Rapture and takes it in the sky-city of Columbia. Players will follow Booker DeWitt, a private eye with a military past; as he will attempt to wipe his debts with the only skill he’s good at – finding people. Aside from obvious story and style differences, this time Bioshock protagonist has a personality, character, and voice, no longer the protagonist is a silent man, trying to survive.Open and bright level design of Columbia shows industrial colonial America in a seemingly endless carnival. But Bioshock is not famous for its visuals, but for its story. Mystery and creative vision of Irrational Games invite players to uncover the secrets of Columbia’s leader - Zachary Comstock and save Elizabeth, the girl, that’s been locked up in the flying city since her birth.Unique weapons and mechanics of Vigor will make encounters different, helping players to adjust to the new found mobility and hook shot, making fights fast-paced and imaginative.")
                            .released(LocalDate.parse("2013-03-26"))
                            .mainImage("https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/fc1/fc1307a2774506b5bd65d7e8424664a7.jpg", "https://media.rawg.io/media/screenshots/bf0/bf07e2c6d2c888d372917d9ef453c8a4.jpg", "https://media.rawg.io/media/screenshots/9d3/9d38833952812ad7888a6dc21699934f.jpg", "https://media.rawg.io/media/screenshots/595/59572d257b6797986e4eabcd1ee023fd.jpg", "https://media.rawg.io/media/screenshots/f71/f71c23eb76f050d6180490e82d58d799.jpg", "https://media.rawg.io/media/screenshots/871/8713411d5332ceb2b4092073a6f5f3f2.jpg", "https://media.rawg.io/media/screenshots/985/985b56daa78e0a23133518d4226e9f97.jpg"))
                            .rating(4.39)
                            .price(91.0)
                            .priceWithSale(91.0 - (91.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Action", "Shooter"))
                            .tags(List.of("Singleplayer", "Steam Achievements", "Atmospheric", "steam-trading-cards", "Full controller support", "Steam Cloud", "Great Soundtrack", "RPG", "Story Rich", "First-Person", "Sci-fi", "FPS", "Fantasy", "Gore", "Controller", "Dystopian", "Steampunk", "Linear", "Alternate History", "Time Travel", "Political"))
                            .platforms(List.of("PlayStation 4", "Xbox 360", "Nintendo Switch", "Linux", "PC", "PlayStation 3", "Xbox One"))
                            .build(),
                    Game.builder()
                            .id("3439")
                            .name("Life is Strange")
                            .description("Interactive storytelling and plot-heavy games gained popularity, and “Life is Strange” arrived as teen mystery adventure. The plot will go through the life of Maxine, a teenager in possession of curious power, allowing her to stop and rewind time, in order to manipulate her surroundings. Max, after the reunion with her friend Chloe, is on the path to uncovering the secrets of Arcadia Bay. Players will have to deal with puzzle solving through the fetch quests, in order to change the world around them. The game puts players in situations, where they’re forced to make a moral choice, going through the decision which may have short-term or long-term consequences. Every choice made by the player will trigger the butterfly effect, surrounding the first playthrough of the game with a lot of emotional struggle, thoughtfully crafted by the developers at Dontnod Entertainment. Life is Strange is third person adventure game, where players might seem just as an observer of the stories, unfolding in front of them.")
                            .released(LocalDate.parse("2015-01-29"))
                            .mainImage("https://media.rawg.io/media/games/562/562553814dd54e001a541e4ee83a591c.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/562/562553814dd54e001a541e4ee83a591c.jpg", "https://media.rawg.io/media/screenshots/edf/edfcbdf85f02f871263dabf1b4f0aa87.jpg", "https://media.rawg.io/media/screenshots/4c6/4c6da2f36396d4ed51f82ba6159fa39b.jpg", "https://media.rawg.io/media/screenshots/6aa/6aa56ef1485c8b287a913fa842883daa.jpg", "https://media.rawg.io/media/screenshots/cb1/cb148b52fe857f5b0b83ae9c01f56d8e.jpg", "https://media.rawg.io/media/screenshots/aea/aea38b33b90054f8fe4cc8bb05253b1d.jpg", "https://media.rawg.io/media/screenshots/c1d/c1d6333b2da0f920e8de10c14d3c6093.jpg"))
                            .rating(4.11)
                            .price(392.0)
                            .priceWithSale(392.0 - (392.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Adventure"))
                            .tags(List.of("Singleplayer", "Atmospheric", "steam-trading-cards", "Full controller support", "Great Soundtrack", "Story Rich", "Third Person", "Female Protagonist", "Dark", "Point & Click", "Short", "Mystery", "Choices Matter", "Memes", "Walking Simulator", "Story", "Multiple Endings", "Episodic", "Time Travel", "Soundtrack", "Time Manipulation", "student", "strange", "photography"))
                            .platforms(List.of("PC", "Linux", "PlayStation 3", "macOS", "iOS", "Xbox 360", "Android", "PlayStation 4", "Xbox One"))
                            .build(),
                    Game.builder()
                            .id("802")
                            .name("Borderlands 2")
                            .description("Sequel to the 4-player cooperative FPS RPG Borderlands, where the new team of Vault Hunters arrives on the infamous planet Pandora in order to get the riches, hidden inside the Vault, and help to free the planet from the Handsome...")
                            .released(LocalDate.parse("2007-08-21"))
                            .mainImage("https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg", "https://media.rawg.io/media/screenshots/01f/01f62d7064838a5c3202acfc61503487.jpg", "https://media.rawg.io/media/screenshots/7f5/7f517e07e36e4af5a7c0b86a7d42853f.jpg", "https://media.rawg.io/media/screenshots/aca/aca089b963a42ec4cbf56b5e5334af8e.jpg", "https://media.rawg.io/media/screenshots/3aa/3aa6f71eba1d64e671bd45826ca96560.jpg", "https://media.rawg.io/media/screenshots/d8e/d8ed29c7c0b41e4013588847944ed446.jpg", "https://media.rawg.io/media/screenshots/146/146e418797aca19296f90d259207414c.jpg"))
                            .rating(4.37)
                            .price(390.0)
                            .priceWithSale(390.0 - (390.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Action", "Shooter"))
                            .tags(List.of("Singleplayer", "Atmospheric", "Great Soundtrack", "RPG", "Story Rich", "First-Person", "Sci-fi", "Partial Controller Support", "Horror", "FPS", "Classic", "Action RPG", "Dark", "Dystopian", "Steampunk", "Alternate History", "Political", "Underwater"))
                            .platforms(List.of("Xbox 360", "PlayStation 3", "iOS", "Nintendo Switch", "Xbox One", "PC", "macOS", "PlayStation 4"))
                            .build(),
                    Game.builder()
                            .id("1030")
                            .name("Limbo")
                            .description("This popular 2D puzzle-platformer creates the atmosphere of isolation, where the player alone can guide the nameless protagonist to his destination. Hostile environments and one-hit deaths may seem difficult, but the game implements a fair amount of checkpoints. The monochrome color palette showcases cartoony proportions of every living thing while making lack of details threatening. Limbo shows you exactly what you encounter, but never how it looks.Limbo uses the atmosphere and sound design of the horror genre while avoiding tropes of the modern horror games. The overarching theme and unique style compensated for the rather short game with an abrupt ending, making Limbo one of the most impactful games for the genre.The simple controls and easy-to-pick-up mechanics help to make a clear distinction, which part of the stage players can interact with, and which part can lead to the quick death. Even though the game is in black and white, this separation is intuitive and natural, so the player would know exactly where to go or what to do.")
                            .released(LocalDate.parse("2010-07-21"))
                            .mainImage("https://media.rawg.io/media/games/942/9424d6bb763dc38d9378b488603c87fa.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/942/9424d6bb763dc38d9378b488603c87fa.jpg", "https://media.rawg.io/media/screenshots/512/512f4bc2092016478ddcb9e7e60aeec0.jpg", "https://media.rawg.io/media/screenshots/63d/63d30699e8fcab9c808e6714d9d3fd59.jpg", "https://media.rawg.io/media/screenshots/de0/de04bbc0fd9904071ef25bf23113c8c4.jpg", "https://media.rawg.io/media/screenshots/eed/eedbbca4ae2debf2d4e23e55d1f6cff7.jpg", "https://media.rawg.io/media/screenshots/59f/59f472b3ed7b414777a29213d70b4d17.jpg", "https://media.rawg.io/media/screenshots/e58/e58d31146e4a9e3786dabcbfc30126bc.jpg"))
                            .rating(4.16)
                            .price(132.0)
                            .priceWithSale(132.0 - (132.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Adventure", "Indie", "Puzzle", "Platformer"))
                            .tags(List.of("Singleplayer", "Atmospheric", "Full controller support", "2D", "Horror", "Difficult", "Controller", "Dark", "controller support", "Short", "Side Scroller", "Physics", "Cinematic", "Puzzle-Platformer", "Surreal", "Minimalist"))
                            .platforms(List.of("Linux", "PS Vita", "Android", "Xbox One", "Nintendo Switch", "iOS", "PC", "macOS", "Xbox 360", "PlayStation 3", "PlayStation 4"))
                            .build(),
                    Game.builder()
                            .id("2454")
                            .name("DOOM (2016)")
                            .description("Return of the classic FPS, Doom (2016) acts as a reboot of the series and brings back the Doomslayer, protagonist of the original Doom games. In order to solve the energy crisis, humanity learned to harvest the energy from Hell, and when something went wrong and a demon invasion has started, it’s up to the player to control the Doomslayer and destroy the evil.Doom is a fast-paced game that restores the concept of instant health packs and leaves the player against armies of Hell with no cover, no health regeneration, or help from anyone. After damaging monsters enough, they will start glowing, which will allow players to perform glory kills to restore some health. While exploring the levels, players will come across secrets, collectible items, or upgrade points for the weapons and armor. The single-player campaign silent protagonist has a noticeable personality. He gets visibly annoyed and angry in his actions during expository cutscenes and forces his way through the game. Multiplayer maps gather players in Deathmatch/”king-of-the-hill” type game modes, with all the weapons from the single-player campaign.")
                            .released(LocalDate.parse("2016-05-13"))
                            .mainImage("https://media.rawg.io/media/games/c4b/c4b0cab189e73432de3a250d8cf1c84e.jpg")
                            .shortScreenshots(List.of("https://media.rawg.io/media/games/c4b/c4b0cab189e73432de3a250d8cf1c84e.jpg", "https://media.rawg.io/media/screenshots/353/353c1e834e7da7d6ceaa6beaff529c29.jpg", "https://media.rawg.io/media/screenshots/e50/e50f822107b8cc6af57aa21d76524149.jpg", "https://media.rawg.io/media/screenshots/ae9/ae9e9f7bfe19c63bd16151f81f81a7ed.jpg", "https://media.rawg.io/media/screenshots/14e/14e33eccb109558b0524761340ff2023.jpg", "https://media.rawg.io/media/screenshots/45d/45d16955ac9e90141b726684a07db02a.jpg", "https://media.rawg.io/media/screenshots/b77/b77629938389a41160d3b2a56eaed568.jpg"))
                            .rating(4.54)
                            .price(657.0)
                            .priceWithSale(657.0 - (657.0 * 0 / 100))
                            .onSale(0.0)
                            .active(true)
                            .featured(false)
                            .isNew(false)
                            .genres(List.of("Action", "Shooter"))
                            .tags(List.of("Singleplayer", "Steam Achievements", "Multiplayer", "Atmospheric", "Full controller support", "Steam Cloud", "Great Soundtrack", "Co-op", "First-Person", "Gore", "FPS", "Online Co-Op", "Moddable", "Demons", "Fast-Paced", "Classic", "Violent", "Arena Shooter", "Mechs", "Action-Adventure", "Sci-fi", "Dark Fantasy", "Retro", "Demons", "Melee Combat", "E-sports", "Competitive", "1990's"))
                            .platforms(List.of("Nintendo Switch", "PlayStation 4", "PC", "Xbox One", "Xbox Series S/X", "PlayStation 5"))
                            .build()
            );
            gameRepository.saveAll(games);
        }
    }
}